### ISSUE TITLE
Create Start Page

### ISSUE THREAD

**Issue by ronnyleibham** [ronnyleibham/capstone-project#1]
**As a user**
**I can**click the Button
**to start** the App 

## Description (text, scribbles, images, designs)
![image](https://user-images.githubusercontent.com/69803458/142996970-9a5bc836-c8f5-49ca-8170-4ecaf35076d9.png)

## Acceptance Criteria
- [x] Only on button push the App should start

## Tasks (for developers)
- [x] Create featur branch
- [x] Setup global styles for whole App
- [x] Create start page
- [x] Create round button with pulsating effect
