### ISSUE TITLE
Create "Take a picture" page

### ISSUE THREAD

**Issue by ronnyleibham** [ronnyleibham/capstone-project#2]
## Value proposition
**As a user**
**I need to** take a photo
**to be able to** use the recognition of the App

## Description (text, scribbles, images, designs)
![image](https://user-images.githubusercontent.com/69803458/143001003-44cfb8f9-e044-425c-8629-90c4e3734d9e.png)

## Acceptance Criteria
- [x] Camera preview should instant be visable
- [x] Button should be very present

## Tasks (for developers)
- [x] Phone camera should be usable
- [x] Auto focus should work
- [x] Picture needs random ID because in next step user decides to move on or take a reshot
- [x] Add Nav Bar **Type 1** with red "take a picture" button (type 2 centered button element is with changed symbol)
- [x] Play typical camera sound when Button is hitted
