### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by ronnyleibham** [ronnyleibham/capstone-project#3]
**As a user**
**I can** click 3 different buttons
**to navigate** through main features of the App 

## Description (text, scribbles, images, designs)
2 different types of nav-bars. They differ just in centered button. 
TYPE 1 style ist with a red button to shot a photo. 
TYPE 2 has a closed iris, similar to camera objectives, in centered position instead the res button from Type 1

TYPE 1
![image](https://user-images.githubusercontent.com/69803458/143029089-067e67e0-3bc6-486f-972b-4d3b34ab2c96.png)

TYPE 2
![image](https://user-images.githubusercontent.com/69803458/143029164-4f147b6b-3752-4dca-925c-0a6e4cd8ec9a.png)

## Acceptance Criteria
- [x] User should be able to navigate always with Search Button (left) and Archive Button (right)
- [x] After taking a shot the red button should be greyed out
- [x] after uploading the red button switches to Iris symbol. When clicked the "take a picture" site is called again.

## Tasks (for developers)
- [x] Create new branch
- [x] Create 2 different Nav-bars
- [x] TYPE 1: set Links to SEARCH (left), function handleTakePhoto() (center) and ARCHIVE (right) pages
- [x] TYPE 2: set Links to SEARCH (left), RECORD (center) and ARCHIVE (right) pages
- [x] TYPE 1 & TYPE 2: company logo in bottom right corner is part of the Nav-Bar and has to be linked to START page
