### ISSUE TITLE
Scanning Progress Bar

### ISSUE THREAD

**Issue by ronnyleibham** [ronnyleibham/capstone-project#7]
## Value proposition
**As a user**
**I see** progress bar
**to be able to** know how long scanning will take

## Description (text, scribbles, images, designs)
![image](https://user-images.githubusercontent.com/69803458/144821040-f4a235ea-2ad4-4e0a-a649-1b455e40cbc9.png)

## Acceptance Criteria
- [ ] Progress bar should show progress
- [ ] After finish auto redirect to Result page

## Tasks (for developers)
- [ ] Taken picture should be uploaded to DeepVA engine
- [ ] Engine sent status automatically and should be catched to fill progress bar
- [ ] After engine sent status that it's finished Tags should be saved in DB
- [ ] Auto relink to results page
