### ISSUE TITLE
Create Result page

### ISSUE THREAD

**Issue by ronnyleibham** [ronnyleibham/capstone-project#8]
## Value proposition
**As a user**
**You see** picture in background and Tags
**to be able to** see first results.

## Description (text, scribbles, images, designs)
![image](https://user-images.githubusercontent.com/69803458/144823608-c1ca26fa-4b32-4854-8af4-71c7e17c9082.png)

## Acceptance Criteria
- [ ] Only first 10 Tags should be visible to keep it simple
- [ ] Hint shows with arrow to button to see full result

## Tasks (for developers)
- [ ] First create Backend interface to communicate with DeepVA engine
- [ ] Use NavBar with closed iris
- [ ] only show 10 first Tags
- [ ]  DeepVA engine delivers result in JSON data where Tags could be fetched from
- [ ] store in online DB and link result to stored picture in DeepVA account
- [ ] don't think about local storaging. Could be later implemented
- [ ] show user via visible hint where to click to see full result. Will lead him to Archive Page
